using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Custom_Exception_Handling
{
    internal class Class1
    {
        internal void Sqrt1(double n)
        {
            //try
            //{
            //    if (n <= 0)
            //    {
            //        throw new CustExp1("Zero not allowed.");
            //    }
            //    double res = Math.Sqrt(n);
            //    Console.WriteLine($"The Square root of number is : {n} is {res}");
            //}
            //catch (CustExp1 e)
            //{
            //    Console.WriteLine($"Custom Exception : {e.ToString()}");
            //}

        }
    }
}
